//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientInformation.ClientInformationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ClientInfoService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientInformationService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ClientInformation.ClientInformationService.CompositeType GetDataUsingDataContract(ClientInformation.ClientInformationService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ClientInformation.ClientInformationService.CompositeType> GetDataUsingDataContractAsync(ClientInformation.ClientInformationService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGenderLookup", ReplyAction="http://tempuri.org/IService1/GetGenderLookupResponse")]
        System.Data.DataSet GetGenderLookup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetGenderLookup", ReplyAction="http://tempuri.org/IService1/GetGenderLookupResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetGenderLookupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAddressTypeLookup", ReplyAction="http://tempuri.org/IService1/GetAddressTypeLookupResponse")]
        System.Data.DataSet GetAddressTypeLookup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAddressTypeLookup", ReplyAction="http://tempuri.org/IService1/GetAddressTypeLookupResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAddressTypeLookupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContactNumberTypeLookup", ReplyAction="http://tempuri.org/IService1/GetContactNumberTypeLookupResponse")]
        System.Data.DataSet GetContactNumberTypeLookup();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetContactNumberTypeLookup", ReplyAction="http://tempuri.org/IService1/GetContactNumberTypeLookupResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetContactNumberTypeLookupAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientInformation.ClientInformationService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientInformation.ClientInformationService.IService1>, ClientInformation.ClientInformationService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ClientInformation.ClientInformationService.CompositeType GetDataUsingDataContract(ClientInformation.ClientInformationService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ClientInformation.ClientInformationService.CompositeType> GetDataUsingDataContractAsync(ClientInformation.ClientInformationService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Data.DataSet GetGenderLookup() {
            return base.Channel.GetGenderLookup();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetGenderLookupAsync() {
            return base.Channel.GetGenderLookupAsync();
        }
        
        public System.Data.DataSet GetAddressTypeLookup() {
            return base.Channel.GetAddressTypeLookup();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAddressTypeLookupAsync() {
            return base.Channel.GetAddressTypeLookupAsync();
        }
        
        public System.Data.DataSet GetContactNumberTypeLookup() {
            return base.Channel.GetContactNumberTypeLookup();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetContactNumberTypeLookupAsync() {
            return base.Channel.GetContactNumberTypeLookupAsync();
        }
    }
}
